### ISSUE TITLE
Add new type of view: Event view

### ISSUE THREAD

**Issue by itssimple** [MultinetInteractive/EduAdmin-WordPress#154]
Some customers mostly market their course templates by a specific event, not by course template.

**Comment by MNKevin** [comment]
There's no description-fields connected to specific events in EduAdmin, since EduAdmin handles this at the Course Template level.
This means that we'd have to fetch the descriptions from the Course Template.

We could probably add the information from Answers on the Event, since these fields usually shows event specific information. (Should require that the answer has ShowExternal = true)
