### ISSUE TITLE
My Profile list the whole companys bookings but only my own certificates

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#259]
Change so the whole companys certificates are shown under Certificates instead of only the ones that I have personally.

Most customers use "My profile" to let a Manager see the bookings for the whole company.
We should then also show the certificates for the whole company.
We need to also show the name of the person with each certificate.

**Comment by itssimple** [comment]
I looked into it, and there's no way to fetch all certificates for a company with the API, but if we get the support to fetch certificates as well, I can implement it!

**Comment by MNKevin** [comment]
Sounds like a great feature!

I'd just like to add that since we don't really have an end customer "Manager"-role in EduAdmin anybody who's able to log in to _My profile_ will be able to see all of their colleagues certificates.

This means that we should probably hide this feature behind a setting in the plugin.

**Comment by itssimple** [comment]
I hate settings :(

**Comment by MNKevin** [comment]
Well if you'd prefer you could always make it an attribute instead. :)
