### ISSUE TITLE
Add support for Reserve lists

### ISSUE THREAD

**Issue by multialgu** [MultinetInteractive/EduAdmin-WordPress#455]
In order to replace the Interest registration that is currently available.

**Comment by mn-osal** [comment]
I think this would require some kind of addition to the EduAdmin API so we can determine if the event actually supports reserve lists or not, since this can be configured on an event basis. If we don't have that information, the end user could potentially open a form for a "reserve list" that is just closed.

This also requires that the customer is using the forms from EduAdmin instead of the WP one. So this cannot replace the WP ones just yet.

Insider information, we're soon releasing a "simple" interest registration form for courses, so we should be able to replace both interest registrations if the customer uses the EduAdmin forms!

**Comment by pmerkland** [comment]
Boom.
![image](https://user-images.githubusercontent.com/21121350/196936335-4628a443-1698-44cd-bd3e-cd58e4c8875b.png)

**Comment by itssimple** [comment]
Only plugins using the EduAdmin forms have support for this.
