### ISSUE TITLE
Add Vat to price

### ISSUE THREAD

**Issue by drilonmaloku** [MultinetInteractive/EduAdmin-WordPress#456]
Hi, can you add a new feature that would allow us to include or exclude vat based on the course when I use this shortcode [eduadmin-detailinfo courseprice] I need to have the vat option as well so some courses will have VAT pre calculated on the price showed.

![image](https://user-images.githubusercontent.com/14080554/190020842-6b646592-861e-40af-b836-22122b521010.png)

**Comment by itssimple** [comment]
There is a setting in the plugin to force the price to show as either:
- Both (Will include inc/ex VAT)
- Inc VAT
- Ex VAT

Will look into making some sort of option for the courseprice attribute to override the setting.

**Comment by drilonmaloku** [comment]
Currently I need it only for some courses, so in this case I will need something like this [eduadmin-detailinfo courseprice include_vat="true"] so on some courses I want to show them with VAT and on some others no.

**Comment by itssimple** [comment]
Work in progress
![image](https://user-images.githubusercontent.com/11502257/191734078-556dc0a7-1b9e-4284-8be8-5fbdd5ae0362.png)


Going to implement it as the following

Default courseprice:
`[eduadmin-detailinfo courseprice]`

Show inc/ex VAT:
`[eduadmin-detailinfo courseprice="both"]`

Only VAT:
`[eduadmin-detailinfo courseprice="inclVat"]`

Without VAT:
`[eduadmin-detailinfo courseprice="exclVat"]`

Reason I'm implementing it like this, is because those options match up with what the option value is called in the plugin settings. Just to make it simple for me to implement. :)
