### ISSUE TITLE
Add required properties to ld+json for Course info for Google Search Structured data

### ISSUE THREAD

**Issue by pmerkland** [MultinetInteractive/EduAdmin-WordPress#511]
https://developers.google.com/search/docs/appearance/structured-data/course-info

According to Google Search Console and the google dev specifications we need to add the following required properties:

"Offers" which is basically a list of price names from the Course Template and/or Events in EduAdmin. I do not know the best way to filter this list. Maybe we already have a function for retrieving the correct prices for a course/event?

"[hasCourseInstance](https://developers.google.com/search/docs/appearance/structured-data/course-info#course-instance-sd)" is also required. Use with "courseSchedule" if for every instance with an actual scheduled Event in EduAdmin and with "courseWorkload" if there are no Events scheduled.
Even though there is a feature to provide a instructor I think we should skip it as most users do not want to show the names of their instructors on their web.

**Comment by pmerkland** [comment]
Also hasCourseInstance.courseMode is a bit tricky. We should at least do "OnDemand": true, from EduAdmin Event API as "Online".
We could also check if the Event has any ActivityModules as "Blended". Otherwise just "Onsite".

Both "Blended" and "Onsite" needs a hasCourseInstance.location

**Comment by pmerkland** [comment]
From Google Search Console:
![image](https://github.com/MultinetInteractive/EduAdmin-WordPress/assets/21121350/e5e0d5d8-1944-4512-bed8-892e25af9b99)

**Comment by itssimple** [comment]
The problem with "Offers" is that it is for the entire course, not the instances, from what I can see. So we can probably only offer the public pricenames on the course itself.

And about the `hasCourseInstance`, if there are no events coming/planned that comes from the API, it won't show up, as the course doesn't have any events. Question is if we should skip the ld+json for those cases.

But it also seems that Google have updated what they require, because I used this tool when I validated that the data was valid before: https://search.google.com/test

So either Google increased their requirements, or something else is wrong, because https://validator.schema.org/ still validates my test page without warnings or errors.

**Comment by itssimple** [comment]
I'm not even sure how to set a date/schedule/workload for on demand courses, as we don't have any real dates or "time to complete" info in the API, as I know of.

**Comment by pmerkland** [comment]
We might have missed some more,
![image](https://github.com/MultinetInteractive/EduAdmin-WordPress/assets/21121350/642341ad-0a14-475d-90cf-fd56c2247003)
![image](https://github.com/MultinetInteractive/EduAdmin-WordPress/assets/21121350/88ca2913-a288-4aff-93ec-c4bdbf87e113)

I guess we do "daily" and try to count the number of days from the Events EventDates if there are any, otherwise calculate based on the Events Start and end dates.

**Comment by pmerkland** [comment]
> Also CourseInstance.courseMode is a bit tricky. We should at least do "OnDemand": true, from EduAdmin Event API as "Online". We could also check if the Event has any ActivityModules as "Blended". Otherwise just "Onsite".
> 
> Both "Blended" and "Onsite" needs a hasCourseInstance.location

Also every CourseInstance needs an courseMode.
